### ISSUE TITLE
Store entered data in localStorage

### ISSUE THREAD

**Issue by svylabs** [svylabs/trustlex-ui#1]
This should address
- selectedToken
- Any entered values by the user: number of bitcoins or the price or any values.
I'm thinking we have to use reducer for this, what are your thoughts?

**Comment by abhishekram404** [comment]
Yes, it is a good idea to use reducers, do you mean we have to use Redux? 
Currently, local Storage and redux are not used in the project but the react hook known as use-context is used for storing current user account, account balance, any entered values by the user like the number of bitcoins, the price, the limit or any values. All these data are stored in the local state but by the use of use-context, it is the same as stored in the global state.

**Comment by svylabs** [comment]
As I understand the data doesn't persist between sessions right? To provide a good experience it would be good if we can persist some data in localstorage and use that data when the page is being loaded

**Comment by abhishekram404** [comment]
yes, you are right, when the page is reloaded. all the previous data disappears. Alright, then the list of data that you want to be stored in the local storage

**Comment by svylabs** [comment]
1. selectedToken
2. Any entered data: 
     - Amount of Bitcoin
     - Amount of Ethereum
     - Limit price
    It also will be good if we initialize these fields with empty values than having "0", then we can show a placeholder text.
These are the only fields I can think of for now.

**Comment by abhishekram404** [comment]
I am confused that if local storage is used to store the selected token, the amount of bitcoin, Ethereum and the limit price. The data stored on local storage should be loaded on the fields or the fields should be empty with a placeholder when the application is reloaded?

**Comment by svylabs** [comment]
I wanted to mean, if there is nothing in localstorage, we can show placeholder values rather than showing 0

**Comment by abhishekram404** [comment]
I got it. The local storage, placeholder and new package for generating QR code is implemented in the code and it is pushed to the Github. please run npm install before you run the code.
