### ISSUE TITLE
[Exchange component] Make some fields non-editable

### ISSUE THREAD

**Issue by svylabs** [svylabs/trustlex-ui#10]
Some fields in the exchange component should be non-editable

<img width="1082" alt="Screenshot 2023-04-01 at 17 16 09" src="https://user-images.githubusercontent.com/64266123/229297876-35af56f1-d226-4bed-a0fa-37218f900fa5.png">

**Comment by Glenapp** [comment]
Already Fixed

**Comment by svylabs** [comment]
Thanks @Glenapp
