### ISSUE TITLE
Wallet file should be downloadable

### ISSUE THREAD

**Issue by svylabs** [svylabs/trustlex-ui#18]
When "Download wallet" is clicked,
1. Check if the password provided matches.
2. Users should be able to download the wallet to a file.

**Comment by Glenapp** [comment]
I have implemented that functionality.
https://www.loom.com/share/65621bdfae5a411caeb73f7901f20bb4

**Comment by Glenapp** [comment]
We have used the browsify and fixed it https://www.loom.com/share/b423df2840f94a7990b61c447f1d724d
