### ISSUE TITLE
Add support for ERC20 tokens

### ISSUE THREAD

**Issue by svylabs** [svylabs/trustlex-ui#20]
1. User should be able to select a new token(Apart from ETH)
2. Adding offer should first "Authorize" the contract to take the amount of tokens.
      example:  Buy 1 BTC using 1000 USDT, should authorize the contract to take 1000 USDT from the user wallet.

**Comment by Glenapp** [comment]
Demo video
https://www.loom.com/share/1c894ecea9c2434e96d983b177449611
