### ISSUE TITLE
offer list not showing up

### ISSUE THREAD

**Issue by svylabs** [svylabs/trustlex-ui#21]
We need to use a different API (https://github.com/svylabs/trustlex-ui/blob/main/src/files/contract.json#L265) rather than listening to events for offers.
first get the total number of orders using this API: https://github.com/svylabs/trustlex-ui/blob/main/src/files/contract.json#L246
And then iterate and get the offers through getOffers API

**Comment by Glenapp** [comment]
I have changed the API for fetching the offers list. As well worked on Load More Buton. Improved the UI experience like firstly on page load. It is connecting the Ethereum node. So we showing the message the "Connecting to the Network"
https://prnt.sc/7aXSkXApfm4u   
![image](https://user-images.githubusercontent.com/94823273/234038998-3923e8f1-7ec3-46a7-9612-4bf747c40ce0.png)
.  After connecting  to the network we are showing Loading list  message. 
![image](https://user-images.githubusercontent.com/94823273/234039207-e6eba1c0-e515-40d4-99ad-c1b83088c049.png)
After loading If there are other items to be loaded in next time. Load more button is coming.
![image](https://user-images.githubusercontent.com/94823273/234039594-a7d3f058-513a-4733-b93f-cc696f421850.png)

**Comment by Glenapp** [comment]
I have implemented the offer list api.
![image](https://user-images.githubusercontent.com/94823273/234254193-ead2e3a7-4d0b-4517-9bd7-5a5cb6527fe8.png)
https://www.loom.com/share/e4441d61ecfe48a9b9fe65b7a3e46a2b
