### ISSUE TITLE
The amount of ETH left to buy went from 0.0003 to 0 even though I only entered 0.0001

### ISSUE THREAD

**Issue by svylabs** [svylabs/trustlex-ui#30]
<img width="1420" alt="Screenshot 2023-05-17 at 16 56 36" src="https://github.com/svylabs/trustlex-ui/assets/64266123/a76895aa-55e2-4163-b35b-2e8fbdfeaf89">

<img width="1391" alt="Screenshot 2023-05-17 at 16 57 11" src="https://github.com/svylabs/trustlex-ui/assets/64266123/50feb8a9-824c-4c8b-8a5d-d06d30b2bce3">

**Comment by Glenapp** [comment]
I have fixed it. In the contract fulll values was going statically. Now I have corrected it user input.
https://www.loom.com/share/d565086c07f94f60a4bbe66663c12d14
