### ISSUE TITLE
Exchange / Add offer

### ISSUE THREAD

**Issue by svylabs** [svylabs/trustlex-ui#31]
<img width="1346" alt="Screenshot 2023-05-17 at 17 17 58" src="https://github.com/svylabs/trustlex-ui/assets/64266123/e33c723d-cf93-49a3-9ea3-d431b89c5dd6">

**Comment by Glenapp** [comment]
Added the dropdwon option for offer valid Till.
https://prnt.sc/lDBqTKmbnm0l  .
And passed the updated value in contract.
Disabled the minimum collateral  select box with 0% default value.

https://prnt.sc/j20w9X6rM75q

https://www.loom.com/share/2410e972a5724230bf38babfa302425e
