### ISSUE TITLE
Exchange / Offer List

### ISSUE THREAD

**Issue by svylabs** [svylabs/trustlex-ui#32]
<img width="1361" alt="Screenshot 2023-05-17 at 17 25 13" src="https://github.com/svylabs/trustlex-ui/assets/64266123/fbeb77ca-1bc8-4872-956c-b7acc14aae07">

**Comment by Glenapp** [comment]
We have fetched the values from contract. we are showing Offer ValidTill value on the behalf of offerValidTill+orderedTime.
https://www.loom.com/share/2410e972a5724230bf38babfa302425e
https://prnt.sc/g80P9fZxkQ1g
