### ISSUE TITLE
Include time left after initiation and dynamic time value

### ISSUE THREAD

**Issue by svylabs** [svylabs/trustlex-ui#33]
<img width="1334" alt="Screenshot 2023-05-17 at 18 22 20" src="https://github.com/svylabs/trustlex-ui/assets/64266123/8d1a5ecf-9120-45ad-96b5-74c6b90645fc">

**Comment by Glenapp** [comment]
I  have fixed it in two cases.
1-when user comes back from exchange page.
2-When user come back from recent Myswap page
https://www.loom.com/share/45d50bd00975482cac8a4fba18987c20
