### ISSUE TITLE
Generate testnet address or production address based on URL

### ISSUE THREAD

**Issue by svylabs** [svylabs/trustlex-ui#36]
Bitcoin address generated should be testnet address or production address depending on the URL.

These two lines need a revision (There is a way to pass which network  - either the bitcoin network or bitcoin testnetwork), accordingly it will produce an address.

https://github.com/svylabs/trustlex-ui/blob/main/src/utils/BitcoinUtils.ts#L22
https://github.com/svylabs/trustlex-ui/blob/main/src/utils/BitcoinUtils.ts#L70

**Comment by Glenapp** [comment]
We have updated these things regarding testnet https://www.loom.com/share/373d7a9195e54875a3bee8e3bb0d84bd

**Comment by Glenapp** [comment]
https://www.loom.com/share/373d7a9195e54875a3bee8e3bb0d84bd
