### ISSUE TITLE
Issues when continuing fulfillment from  Recent page

### ISSUE THREAD

**Issue by svylabs** [svylabs/trustlex-ui#42]
<img width="779" alt="Screenshot 2023-05-19 at 20 24 45" src="https://github.com/svylabs/trustlex-ui/assets/64266123/ba299b87-ba35-4df9-be9b-7b5fa80966e6">

**Comment by Glenapp** [comment]
Bug at Order from recent page is fixed.
https://www.loom.com/share/872080e8019045808f8bd9b2f0e9d78f

**Comment by Glenapp** [comment]
https://www.loom.com/share/6e34d93bb0d24ddb9a0caba391285321
