### ISSUE TITLE
"Left to buy" is more than the "ETH to sell"

### ISSUE THREAD

**Issue by svylabs** [svylabs/trustlex-ui#46]
<img width="1477" alt="Screenshot 2023-05-23 at 18 23 30" src="https://github.com/svylabs/trustlex-ui/assets/64266123/5b7344fa-a749-4ac8-b193-ea33ae6aef50">

**Comment by Glenapp** [comment]
Reseaon: I found the reason behind this. When order is expired. We are decreasing the satoshi to reserved amount and updating the left to buy amount. We are enabling if the order is expired. user can place order again. So in that case orders are placed multiple time and expiring then satoshi to reserve decreasing multiple times. resultant left to buy amount is increasing.Becausing  there is no marking if to a fullfillment order request if it is expired and satoshi to reserve descreses.
https://www.loom.com/share/596cffa0fa8f41f886ff7ba494fa7ee0Solution:

 We have fixed out that problem . I have  update the contract function  initiateFulfillment()  . tested that functions various time. Deployed it again and again  for testing.
In the contract , I have set the order expiry time 1 minute for testing . Later on I will change.

https://www.loom.com/share/33c49c08be504be7a930bfa0f74ad2dd
