### ISSUE TITLE
Fulfilled offer still showing "Initiated", doesn't allow initiation

### ISSUE THREAD

**Issue by svylabs** [svylabs/trustlex-ui#48]
<img width="1406" alt="Screenshot 2023-05-24 at 18 39 30" src="https://github.com/svylabs/trustlex-ui/assets/64266123/105bc78f-9f1d-4bb3-8414-3fbb88316df3">

**Comment by svylabs** [comment]
<img width="1380" alt="Screenshot 2023-05-24 at 18 45 21" src="https://github.com/svylabs/trustlex-ui/assets/64266123/cea6c9b6-7283-4259-8cad-eb9a57f9f803">

**Comment by Glenapp** [comment]
We have fixed out.
