### ISSUE TITLE
Home page - dynamic values

### ISSUE THREAD

**Issue by svylabs** [svylabs/trustlex-ui#61]
<img width="1451" alt="Screenshot 2023-07-01 at 11 58 11" src="https://github.com/svylabs/trustlex-ui/assets/64266123/36af1468-f719-4e49-aefa-b6be446c798d">

We need dynamic values for 
1. number of asset pairs
2. Total value locked
3. Total transaction volume.
We need to use external price feed for computing 2 & 3: We can use chainlink price feeds for this purpose: https://docs.chain.link/data-feeds/price-feeds/addresses - where we can read some values onchain contracts

**Comment by svylabs** [comment]
For total transaction volume:

Here is how to aggregate the BTC value:

1. Get all the transactions hashes(in PAYMENT_SUCCESSFUL event)
2. For each transaction hash lookup the transaction detail in Bitcoin RPC.
3. Within each transaction, check for the presence of outputHash by iterating all outputs in the transaction and taking its sha256 hash and aggregate the value in that output.
4. Total aggregated value in satoshis should be multiplied with price per satoshi to get the total transaction volume.

**Comment by Glenapp** [comment]
We have updated the contract Ui and done the development 

https://www.loom.com/share/de4a0d9d46ab4611b4032305a81406fc

**Comment by Glenapp** [comment]
Feedback by client.
https://prnt.sc/rOMgmvBzAB2c
